export const moughataaOptions = [
  { label: 'Nema', value: 'NEMA' },
  { label: 'Amourj', value: 'AMOURJ' },
  { label: 'Bassiknou', value: 'BASSIKNOU' },
  { label: 'Djiguenni', value: 'DJIGUENNI' },
  { label: 'Timbedra', value: 'TIMBEDRA' },
  { label: 'Oualata', value: 'OUALATA' },
  { label: 'Nbeiket Lahwach', value: 'NBEIKET_LAHWACH' },
  { label: 'Adelgrou', value: 'ADELGROU' },
  { label: 'Aioun', value: 'AIOUN' },
  { label: 'Tamcheket', value: 'TAMCHEKET' },
  { label: 'Koubenni', value: 'KOUBENNI' },
  { label: 'Tintane', value: 'TINTANE' },
  { label: 'Touil', value: 'TOUIL' },
  { label: 'Kiffa', value: 'KIFFA' },
  { label: 'Kankoussa', value: 'KANKOUSSA' },
  { label: 'Boumdeid', value: 'BOUMDEID' },
  { label: 'Guerou', value: 'GUEROU' },
  { label: 'Barkeol', value: 'BARKEOL' },
  { label: 'Kaedi', value: 'KAEDI' },
  { label: 'Monguel', value: 'MONGUEL' },
  { label: 'Maghama', value: 'MAGHAMA' },
  { label: 'Mbout', value: 'MBOUT' },
  { label: 'Lexeiba 1', value: 'LEXEIBA1' },
  { label: 'Aleg', value: 'ALEG' },
  { label: 'Bababe', value: 'BABABE' },
  { label: 'Mbagne', value: 'MBAGNE' },
  { label: 'Magta Lahjar', value: 'MAGTALAHJAR' },
  { label: 'Boghe', value: 'BOGHE' },
  { label: 'Male', value: 'MALE' },
  { label: 'Rosso', value: 'ROSSO' },
  { label: 'Ouad Naga', value: 'OUAD_NAGA' },
  { label: 'Keur Macene', value: 'KEUR_MACENE' },
  { label: 'Rkiz', value: 'RKIZ' },
  { label: 'Boutilimit', value: 'BOUTILIMIT' },
  { label: 'Mederdra', value: 'MEDERDRA' },
  { label: 'Tekane', value: 'TEKANE' },
  { label: 'Atar', value: 'ATAR' },
  { label: 'Aoujeft', value: 'AOUJEFT' },
  { label: 'Ouadane', value: 'OUADANE' },
  { label: 'Chinguitti', value: 'CHINGUITTI' },
  { label: 'Nouadhibou', value: 'NOUADHIBOU' },
  { label: 'Chami', value: 'CHAMI' },
  { label: 'Tidjikja', value: 'TIDJIKJA' },
  { label: 'Moudjeria', value: 'MOUDJERIA' },
  { label: 'Tichit', value: 'TICHIT' },
  { label: 'Selibaby', value: 'SELIBABY' },
  { label: 'Ould Yenge', value: 'OULD_YENGE' },
  { label: 'Ghabou', value: 'GHABOU' },
  { label: 'Wompou', value: 'WOMPOU' },
  { label: 'Zoueratt', value: 'ZOUERATT' },
  { label: 'Fdeirick', value: 'FDEIRICK' },
  { label: 'Bir Moghrein', value: 'BIR_MOGHREIN' },
  { label: 'Akjoujt', value: 'AKJOUJT' },
  { label: 'Bennechab', value: 'BENNECHAB' },
  { label: 'Tevragh Zeina', value: 'TEVRAGH_ZEINA' },
  { label: 'Sebkha', value: 'SEBKHA' },
  { label: 'Ksar', value: 'KSAR' },
  { label: 'Dar Naim', value: 'DAR_NAIM' },
  { label: 'Toujounine', value: 'TOUJOUNINE' },
  { label: 'Teyaret', value: 'TEYARET' },
  { label: 'Arafat', value: 'ARAFAT' },
  { label: 'El Mina', value: 'EL_MINA' },
  { label: 'Riyad', value: 'RIYAD' },
];
